### ISSUE TITLE
add_two_numbers 

### ISSUE THREAD

**Issue by Kiki-Jiji** [best-practice-and-impact/example-package-r#1]
# add_two_numbers function in samplefunction.R

If I was being pernickety (and annoying :P) then:
I noticed that the function will add two numbers but also has different behaviour if given a list?

```
> add_two_numbers(1, c(1,2))
[1] 2 3
````

**Comment by zarbspace** [comment]
I've fixed this.  The function now sums up inputs with multiple elements before adding together to generate a total.
